<div id="userinfo"><p>Dobrodošli, <?= $this->user->fullname ?> | <a href="<?= $this->baseUrl() ?>/admin/auth/logout">Logout</a></p></div>
<div class="container_12" id="midsection">
	<div class="grid_12">
		<h2>Dobrodošli, <?= $this->user->fullname ?>.</h2>
		<p>
			TODO:
		</p>
		<ul>
			<li>Pregled zadnjih promjena: Komentari, Pitanja, Poruke...</li>
			<li>Last visited</li>
			<li>Front Page</li>
		</ul>
	</div>
</div>
