<div id="userinfo"><p>Dobrodošli, <?= $this->user->fullname ?> | <a href="<?= $this->baseUrl() ?>/admin/auth/logout">Logout</a></p></div>
<div class="toolbar">
	<div class="container_12" id="midsection">
			<ul>

			</ul>
	</div>
</div>
<div class="container_12" id="midsection">
	<div class="grid_12">
		<h2>Dobrodošli, <?= $this->user->fullname ?>.</h2>
		<p>
			TODO:
		</p>
		<ul>
			<li>Pregled zadnjih promjena: Komentari, Pitanja, Poruke...</li>
			<li>Last visited</li>
			<li>Front Page</li>
		</ul>
	</div>
</div>
<p class="clear"></p>
<p>&nbsp;</p>

<div id="programi"> 
	<div class="container_12" style="margin-left: auto; margin-right: auto;">
		<div id="prog1" class="grid_4 alpha program">
			<h2>Career Coaching Program</h2>
			<a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/prog1_career.jpg" /></a>
			<p><textarea style="width: 100%; height: 80px;"></textarea></p>
		</div>
		<div id="prog2" class="grid_4 program">
			<h2>Self-Development Program</h2>
			<a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/prog2_selfdev.jpg" /></a>
			<p><textarea style="width: 100%; height: 80px;"></textarea></p>
		</div>
		<div id="prog3" class="grid_4 omega program">
			<h2>Student Management Program</h2>
			<a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/prog3_student.jpg" /></a>
			<p><textarea style="width: 100%; height: 80px;">Nam eget sem sit amet šest varius auctor. Cras sem. Ut hendrerit, libero đut porta ornare, žipsum ipsum consectetuer est, ut tristique lectus mi ac eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</textarea></p>
		</div>
	</div>
	<span class="clear"></span>
</div>
