<div class="container_16" id="midsection">
	<div class="grid_3 sidebar alpha">	
	
		<ul class="sidemenu">
			<?= $this->leftmenu; ?>
		</ul>
	<?= $this->leftsidebar; ?>
	</div>
	<div class="grid_10">
		<h1><?= $this->page->title ?></h1>
		<?php
			if($this->page->text != "")
				echo $this->page->text;
			else
			{
				foreach($this->subelements as $item):
				?>
					<p><a href="<?= $this->baseUrl() . "/" . $this->page->slug . "/" . $item->slug ?>"><?= $item->title ?></a></p>
				<?php
				endforeach;
			}
		?>
	</div>
	<div class="grid_3 omega sidebar"> &nbsp;
		<?= $this->rightsidebar; ?>
	</div>
</div>
