<script type="text/javascript">	 

	$.fn.showsubmenu = function()
	{
		$(".sidesubmenu").hide("slow");
		this.toggle("slow");
	}
	

</script>

<div class="container_16" id="midsection">
	<div class="grid_3 sidebar alpha">
			<ul class="sidemenu">
				<li>
					<a href="#" onclick="$('#sidesubtab1').showsubmenu(); return false;"><img src="<?= $this->baseUrl() ?>/images/icon_prospekta.png" class="icon"/>Grupe<br/> Prospekta</a>
					<ul class="sidesubmenu" id="sidesubtab1" style="display: none;">
						<li><a href="#">Galerija slika</a></li>
						<li><a href="#">Video</a></li>
						<li><a href="#">Uratci naših polaznika</a></li>
						<li><a href="#">Caffe seminar</a></li>
						<li><a href="#">PRO sportivo</a></li>
						<li><a href="#">Feedback polaznika</a></li>
					</ul>
				
				</li>
				<li>
					<a href="#" onclick="$('#sidesubtab2').showsubmenu(); return false;"><img src="<?= $this->baseUrl() ?>/images/icon_group.png" class="icon"/>Studentske<br/> udruge</a>
					<ul class="sidesubmenu" id="sidesubtab2" style="display: none;">
						<li><a href="#">eStudent</a></li>
						<li><a href="#">AIESEC</a></li>
						<li><a href="#">Udruge, javite se!</a></li>
					</ul>	
				</li>
				<li>
					<a href="#" onclick="$('#sidesubtab3').showsubmenu(); return false;"><img src="<?= $this->baseUrl() ?>/images/icon_game.png" class="icon"/>Zanimljivo<br/> i zabavno</a>
					<ul class="sidesubmenu" id="sidesubtab3" style="display: none;">
						<li><a href="#">Za vašu inspiraciju</a></li>
						<li><a href="#">Nepoznato o poznatima</a></li>
						<li><a href="#">Znate li da...</a></li>
						<li><a href="#">Tema tjedna</a></li>
					</ul>	
				</li>
				<li>
					<a href="#" onclick="$('#sidesubtab4').showsubmenu(); return false;"><img src="<?= $this->baseUrl() ?>/images/icon_link.png" class="icon"/>Korisni<br/> linkovi</a>
					<ul class="sidesubmenu" id="sidesubtab4" style="display: none;">
						<li><a href="#">Student</a></li>
						<li><a href="#">Posao</a></li>
						<li><a href="#">Zabava</a></li>
						<li><a href="#">Ljubav</a></li>
						<li><a href="#">Podrška</a></li>
						<li><a href="#">Prehrana</a></li>
						<li><a href="#">Šport</a></li>
					</ul>	
				</li>
				<li><a href="#"><img src="<?= $this->baseUrl() ?>/images/icon_mail_send.png" class="icon"/>Preporuči<br/> prospektu</a></li>
			</ul>
		<?php foreach($this->leftsidebar as $item): ?>
			<h3><?= $item->title; ?></h3>
			<?= $item->text; ?>
		<?php endforeach; ?>
	</div>
	<div class="grid_10">
		<h1><?= $this->page->title ?></h1>
		<?= $this->page->text ?>
	</div>
	<div class="grid_3 omega sidebar"> &nbsp;
		<?php foreach($this->rightsidebar as $item): ?>
			<h3><?= $item->title; ?></h3>
			<?= $item->text; ?>
		<?php endforeach; ?>
	</div>
</div>
