<script type="text/javascript">	 
	$.fn.showsubmenu = function()
	{
		$(".sidesubmenu").hide("slow");
		this.toggle("slow");
	}
</script>
<div class="container_16" id="midsection">
	<div class="grid_3 alpha sidebar">
		<ul class="sidemenu">
			<?= $this->leftmenu; ?>
		</ul>
	</div>
	<div class="grid_10 article">
		<h1><?= $this->article->title ?></h1>
		<?= $this->article->text ?>
		<h2>Komentari</h2>
	</div>
	<div class="grid_3 omega sidebar">
		<p>
			<a href="#" onclick="window.print(); return false;"><img src="<?= $this->baseUrl; ?>/images/icon_print.png" style="vertical-align: text-top" /> Ispiši</a>
		</p><p>	<a href="#"><img src="<?= $this->baseUrl; ?>/images/icon_mail_send.png" style="vertical-align: text-top" /> Pošalji prijatelju</a>
		</p>
	</div>
</div>