<script type="text/javascript">	 

	$.fn.showsubmenu = function()
	{
		$(".sidesubmenu").hide("slow");
		this.toggle("slow");
	}
	

</script>

<div class="container_12">
		<div class="grid_2 alpha sidebar">
			<ul class="sidemenu">
				<li>
					<a href="#" onclick="$('#sidesubtab1').showsubmenu(); return false;">Grupe Prospekta</a>
					<ul class="sidesubmenu" id="sidesubtab1" style="display: none;">
						<li><a href="#">Galerija slika</a></li>
						<li><a href="#">Video</a></li>
						<li><a href="#">Uratci naših polaznika</a></li>
						<li><a href="#">Caffe seminar</a></li>
						<li><a href="#">PRO sportivo</a></li>
						<li><a href="#">Feedback polaznika</a></li>
					</ul>
				
				</li>
				<li>
					<a href="#" onclick="$('#sidesubtab2').showsubmenu(); return false;">Studentske udruge</a>
					<ul class="sidesubmenu" id="sidesubtab2" style="display: none;">
						<li><a href="#">eStudent</a></li>
						<li><a href="#">AIESEC</a></li>
						<li><a href="#">Udruge, javite se!</a></li>
					</ul>	
				</li>
				<li>
					<a href="#" onclick="$('#sidesubtab3').showsubmenu(); return false;">Zanimljivo i zabavno</a>
					<ul class="sidesubmenu" id="sidesubtab3" style="display: none;">
						<li><a href="#">Za vašu inspiraciju</a></li>
						<li><a href="#">Nepoznato o poznatima</a></li>
						<li><a href="#">Znate li da...</a></li>
						<li><a href="#">Tema tjedna</a></li>
					</ul>	
				</li>
				<li>
					<a href="#" onclick="$('#sidesubtab4').showsubmenu(); return false;">Korisni linkovi</a>
					<ul class="sidesubmenu" id="sidesubtab4" style="display: none;">
						<li><a href="#">Student</a></li>
						<li><a href="#">Posao</a></li>
						<li><a href="#">Zabava</a></li>
						<li><a href="#">Ljubav</a></li>
						<li><a href="#">Podrška</a></li>
						<li><a href="#">Prehrana</a></li>
						<li><a href="#">Šport</a></li>
					</ul>	
				</li>
				<li><a href="#">Preporuči prospektu</a></li>
			</ul>
		</div>
		<div id="content" class="grid_5">
			<?php foreach($this->news as $entry) : ?>
				<h3><a href="<?= $this->baseUrl()?>/novosti/<?= $this->escape($entry->slug) ?>"><?= $this->escape($entry->title) ?></a></h3>
				<?= $entry->intro;?>
				<p><small>Teme: 
					<?php $tags = explode(" ", $entry->tags); $i = 0; ?>
					
					<?php foreach($tags as $tag): ?>
						<a href="<?= $this->baseUrl()?>/teme/<?= $this->escape($tag) ?>"><?= $this->escape($tag) ?></a><?php $i++; if($i < count($tags)) echo(", ") ?>
					<?php endforeach; ?></small>
				</p>
				<?php if($entry->text != ""): ?>
					<p><a href="<?= $this->baseUrl() ?>/novosti/<?= $this->escape($entry->slug) ?>">Nastavi &raquo;</a></p>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
		<div id="content2" class="grid_5 omega">
			<?php foreach($this->news as $entry) : ?>
				<h3><a href="<?= $this->baseUrl()?>/novosti/<?= $this->escape($entry->slug) ?>"><?= $this->escape($entry->title) ?></a></h3>
				<?= $entry->intro;?>
				<p><small>Teme: 
					<?php $tags = explode(" ", $entry->tags); $i = 0; ?>
					
					<?php foreach($tags as $tag): ?>
						<a href="<?= $this->baseUrl()?>/teme/<?= $this->escape($tag) ?>"><?= $this->escape($tag) ?></a><?php $i++; if($i < count($tags)) echo(", ") ?>
					<?php endforeach; ?></small>
				</p>
				<?php if($entry->text != ""): ?>
					<p><a href="<?= $this->baseUrl() ?>/novosti/<?= $this->escape($entry->slug) ?>">Nastavi &raquo;</a></p>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>

	<span class="clear"></span>
</div>