<div class="container_12" id="maincontent">
	<div class="grid_12">
		<div class="grid_2 alpha sidebar">
			<ul class="menu">
				<li><a href="#">Grupe Prospekta</a></li>
				<li><a href="#">Studentske udruge</a></li>
				<li><a href="#">Zanimljivo i zabavno</a></li>
				<li><a href="#">Korisni linkovi</a></li>
				<li><a href="#">Preporuči prospektu</a></li>
			</ul>
		</div>
		<div id="content" class="grid_5">
			<?php foreach($this->news as $entry) : ?>
				<h3><a href="<?= $this->baseUrl()?>/novosti/<?= $this->escape($entry->slug) ?>"><?= $this->escape($entry->title) ?></a></h3>
				<?= $entry->intro;?>
				<p><small>Teme: 
					<?php $tags = explode(" ", $entry->tags); $i = 0; ?>
					
					<?php foreach($tags as $tag): ?>
						<a href="<?= $this->baseUrl()?>/teme/<?= $this->escape($tag) ?>"><?= $this->escape($tag) ?></a><?php $i++; if($i < count($tags)) echo(", ") ?>
					<?php endforeach; ?></small>
				</p>
				<?php if($entry->text != ""): ?>
					<p><a href="<?= $this->baseUrl() ?>/novosti/<?= $this->escape($entry->slug) ?>">Nastavi &raquo;</a></p>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
		<div id="content2" class="grid_5 omega">
			<?php foreach($this->news as $entry) : ?>
				<h3><a href="<?= $this->baseUrl()?>/novosti/<?= $this->escape($entry->slug) ?>"><?= $this->escape($entry->title) ?></a></h3>
				<?= $entry->intro;?>
				<p><small>Teme: 
					<?php $tags = explode(" ", $entry->tags); $i = 0; ?>
					
					<?php foreach($tags as $tag): ?>
						<a href="<?= $this->baseUrl()?>/teme/<?= $this->escape($tag) ?>"><?= $this->escape($tag) ?></a><?php $i++; if($i < count($tags)) echo(", ") ?>
					<?php endforeach; ?></small>
				</p>
				<?php if($entry->text != ""): ?>
					<p><a href="<?= $this->baseUrl() ?>/novosti/<?= $this->escape($entry->slug) ?>">Nastavi &raquo;</a></p>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
	</div>
	<span class="clear"></span>
</div>