<div id="messagebar"><div id="message" style="display: none"><?= $this->message ?></div></div>
<div id="userinfo"><p>Dobrodošli, <?= $this->user->fullname ?> | <a href="<?= $this->baseUrl() ?>/admin/auth/logout">Logout</a></p></div>
<div class="toolbar">
	<div class="container_12" id="midsection">
			<ul>
			<li class="button save" id="save"><a href="#">Spremi</a></li>
			<li class="button delarticle" id="delete"><a href="#">Odustani</a></li>
		</ul>
	</div>
</div>
<div class="container_12" id="midsection">
	<script language="javascript" type="text/javascript">
		<?php if($this->menu->id == -1): ?>
			var lock = false; 
		<?php else: ?>
			var lock = true;
		<?php endif; ?>
		$(document).ready(function() {
			
			$("#save").click( function () {
				if($("#slug").attr("value") == "" ) { showMessage("Ispunite polje za slug."); return; }
				if($("#title").attr("value") == "" ) { showMessage("Ispunite polje za naslov."); return; }
				$("#editor").submit();
			} );
			
			$("#title").focus(function() { 
				if($("#title").attr("value") == "Naslov") $("#title").attr("value", "");
			 });
			 
			$("#title").blur(function() { 
				if($("#title").attr("value") == "") $("#title").attr("value", "Naslov");
			 });
			 
			$("#description").focus(function() { 
				if($("#description").attr("value") == "Opis") $("#description").attr("value", "");
			 });
			 
			$("#description").blur(function() { 
				if($("#description").attr("value") == "") $("#description").attr("value", "Opis");
			 });
			
		});
	
		function generateSlug(text)
		{
		    var text_array = text.split(" ");
		    text = text_array.join("-");
		    text = text.toLowerCase()
			return text;
		}
	</script>

	<div class="grid_12">
		<h2><?= ($this->menu->id == "-1") ? 'Nova stavka u izborniku "' . $this->menu->menu . '"' : 'Izmjena stavke "' . $this->menu->menu . '"' ?></h2>
		<!-- <?= $this->menu->parentid ?>  -->
		<form method="post" action="<?= $this->baseUrl(); ?>/admin/menu/save" class="editor" name="editor" id="editor">
			<input type="hidden" name="id" value="<?= $this->menu->id; ?>" />
			<input type="hidden" id="continue" name="continue" value="0" />
			<input type="hidden" name="type" value="page" />
			<input type="hidden" name="menu" value="<?= $this->menu->menu ?>" />
			<div id="content" class="grid_9 alpha">
				<p><input type="text" name="title" id="title" class="big" value="<?= ($this->menu->title != "") ? $this->menu->title : "Naslov" ; ?>" /></p>
				<p><input type="text" name="description" id="description" class="big" value="<?= ($this->menu->description != "") ? $this->menu->description : "Opis" ; ?>" /></p>
				<h3>Pozicija u izborniku</h3>
				<p>
					<select name="parentid">
						<option value="-1">Uvrsti na najvišoj razini</option>
						<optgroup label="Uvrsti pod:" >							
							<?php foreach($this->menuitems as $curpath): if($curpath["id"] == $this->menu->id) continue; ?><option value="<?= $curpath["id"] ?>" <?= ($curpath["id"] == $this->menu->parentid) ? 'selected="selected"' : ""; ?>><?= str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;", $curpath["depth"]-1) . $curpath["title"] ?></option>
							<?php endforeach; ?>
						</optgroup>
					</select>
				</p>
				<h3>Vrsta stavke</h3>
				<p>
					<input type="radio" name="type" value="page" id="radiopage" <?= ("page" == $this->menu->type) ? 'checked="checked"' : ""; ?> onclick="$('#targetlink').hide().attr('name', ''); $('#targetpage').show().attr('name', 'target');"/><label for="radiopage">Stranica</label> 
					<input type="radio" name="type" value="link" id="radiolink" <?= ("link" == $this->menu->type) ? 'checked="checked"' : ""; ?> onclick="$('#targetpage').hide().attr('name', ''); $('#targetlink').show().attr('name', 'target');"/><label for="radiolink">Link</label>
				</p>
				<p>
					<select name="<?php if($this->menu->type == "page") echo "target"; else echo "targetx"; ?>" id="targetpage" <?= ($this->menu->type == "link") ? 'style="display: none;"' : ""; ?>>
						<option value="-2">Bez linka</option>
						<option value="-1">Početna stranica</option>
						<optgroup label="Ostale stranice">
							<?php foreach($this->pages as $curpage): ?><option value="<?= $curpage["id"] ?>" <?= ($curpage["id"] == $this->menu->target) ? 'selected="selected"' : ""; ?>><?= str_replace("/", " &raquo; ", $curpage["path"]) ?></option><?php endforeach; ?>
						</optgroup>
					</select>
					<input type="text" name="<?php if($this->menu->type == "link") echo "target"; else echo "targetx"; ?>" id="targetlink" value="<?= $this->menu->target ?>" <?= ($this->menu->type == "page") ? 'style="display: none;"' : ""; ?> />
				</p>		
			</div>

			<div class="grid_3 omega sidebar">
				<h3>Opcije</h3>
				<p>
					<input type="checkbox" name="published" id="published" <?= $this->menu->published ? "checked='checked'" : ""; ?> value="1" /> <label for="published">Stavka je objavljen</label><br/>
				</p>

			</div>
		</form>
	</div>
</div>