<div class="container_16" id="midsection">
	<div class="grid_3 sidebar alpha">
		<ul class="sidemenu">
			<?= $this->leftmenu; ?>
		</ul>
	</div>
	<div class="grid_10">
		<h1>Upiti i prijave</h1>
		<form class="userform" action="<?= $this->baseUrl ?>/kontakt/prijave2" method="post">
			<p class="required">Crvena polja su obavezna</p>
			<h3>Osobni podaci</h3>
			<p>
				<span><label for="ime">Ime</label><input type="text" name="ime" id="ime" class="text required" /></span>
				<span><label for="prezime">Prezime</label><input type="text" name="prezime" id="prezime" class="text required" /></span>
				<span><label for="email">E-Mail</label><input type="text" name="email" id="email" class="text required" /></span>
				<span><label for="tel">Tel/Mob</label><input type="text" name="tel" id="tel" class="text" /></span>
			</p>
			<h3>Programi</h3>
			<p>
				<input id="progcheck" type="checkbox" onclick="if($(this).attr('checked')) $('.programi').show(0); else $('.programi').hide(0); "> <label for="progcheck"><strong>Prijavi se na tečaj</strong></label><br/>
				<span class="programi" style="display: none"><label for="career">Career Coaching</label><input type="checkbox" name="career" id="career" value="1" /></span>
				<span class="programi" style="display: none"><label for="selfdev">Self-development</label><input type="checkbox" name="selfdev" id="selfdev" value="1" /></span>
				<span class="programi" style="display: none"><label for="student">Student management</label><input type="checkbox" name="student" id="student" value="1" /></span>
			</p>
			<p>&nbsp;</p>
			<h3>Upiti, dodatne informacije, komentari</h3>
				<p><textarea name="info"></textarea><br style="clear: both;" /></p>
			<p>&nbsp;</p>
			<p><input type="submit" value="Pošalji &raquo;" class="button" /></p>
		</form>
		<p class="clear">&nbsp;</p>
	</div>
	<div class="grid_3 omega sidebar"> &nbsp;
	</div>
</div>