<div id="userinfo"><p>Dobrodošli, <?= $this->user->fullname ?> | <a href="<?= $this->baseUrl() ?>/admin/auth/logout">Logout</a></p></div>
<div class="toolbar">
	<div class="container_12" id="midsection">
			<ul>
			<li class="button save" id="save"><a href="#">Spremi</a></li>
			<li class="button save" id="savepublish"><a href="#">Spremi i objavi</a></li>
			<li class="button delarticle" id="delete"><a href="#">Odustani</a></li>
		</ul>
	</div>
</div>
<div class="container_12" id="midsection">
	<script language="javascript" type="text/javascript">
		var lock = false; 
		$(document).ready(function() {
			
			$("#title").slug({hide: false, lock: lock });
			$("#lock").click( function(event) {
				if(lock == false)
				{
					$("#lock").attr("src", "<?= $this->baseUrl(); ?>/images/icon_lock.png");
					$("#lock").attr("title", "Zaključano - Moguća je samo ručna promjena sluga.");
					lock = true;
				}
				else
				{
					$("#lock").attr("src", "<?= $this->baseUrl(); ?>/images/icon_lock_unlock.png");
					$("#lock").attr("title", "Otključano - Promjena naslova mjenja i slug");
					lock = false;
				}
			});
			
			$("#save").click( function () {
				if($("#slug").attr("value") == "" ) { window.alert("Ispunite polje za slug."); return; }
				if($("#title").attr("value") == "" ) { window.alert("Ispunite polje za naslov."); return; }
				$("#editor").submit();
			} );
			
			$("#savepublish").click( function () {
			
				$("#published").attr("checked", "checked");
				if($("#slug").attr("value") == "" ) { window.alert("Ispunite polje za slug."); return; }
				if($("#title").attr("value") == "" ) { window.alert("Ispunite polje za naslov."); return; }
				$("#editor").submit();
			} );
			
		});
	
		function generateSlug(text)
		{
		    var text_array = text.split(" ");
		    text = text_array.join("-");
		    text = text.toLowerCase()
			return text;
		}
	</script>

	<div class="grid_12">
		<h2>Izmjena članka</h2>
		<form method="post" action="<?= $this->baseUrl(); ?>/admin/article/update" class="editor" name="editor" id="editor">
			<input type="hidden" name="category" value="<?= $this->article->category; ?>" />
			<input type="hidden" name="id" value="<?= $this->article->id; ?>" />
			<input type="hidden" name="modified" value="<?= $this->article->modified; ?>" />
			<div id="content" class="grid_9 alpha">
				<p><input type="text" name="title" id="title" class="big" value="<?= $this->article->title; ?>" /></p>
				<p><a href="#" id="slugbutton"><img id="lock" src="<?= $this->baseUrl(); ?>/images/icon_lock_unlock.png" title="Otključano - Promjena naslova mjenja i slug."/></a><input type="text" name="slug" id="slug" class="slug" value="<?= $this->article->slug; ?>"  /> </p>
				<p><?= $this->editor ?></p>		
				<h2>Attachmenti</h2>
				<p>
					Ovaj članak trenutno nema ni jedan attachment.<br/>
					<a href="#">Izaberi attachment</a> | <a href="#">Uploadaj novi attachment</a>
				</p> 
			</div>

			<div class="grid_3 omega sidebar">
				<p><input type="checkbox" name="published" id="published" <?= $this->article->published ? "checked='checked'" : ""; ?> value="1" /> <label for="published">Članak je objavljen</label><br/>
				<input type="checkbox" name="published" id="comments" <?= $this->article->comments ? "checked='checked'" : ""; ?> value="1" /> <label for="comments">Komentari su dozvoljeni</label></p>
				<p>
					<select name="category">
						<optgroup label="Kategorija">
						<?php foreach($this->categories as $cat): ?>
							<option value="<?= $cat->category ?>"<?php if($this->article->category == $cat->category) echo ' selected="selected"' ?>><?= $cat->category ?></option>
						<?php endforeach; ?>
						</optgroup>
					</select>
				</p>
			</div>
		</form>
	</div>
</div>