<div id="userinfo"><p>Dobrodošli, <?= $this->user->fullname ?> | <a href="<?= $this->baseUrl() ?>/admin/auth/logout">Logout</a></p></div>
<div class="container_12" id="midsection">
	<div id="content" class="grid_12">
			<ul class="toolbar">
				<li class="button newarticle" id="new"><a href="<?= $this->baseUrl() ?>/admin/article/new">Novi članak</a></li>
				<li class="button editarticle" id="edit"><a href="#">Izmjeni članak</a></li>
				<li class="button delarticle" id="delete"><a href="#">Izbriši izabrane</a></li>
				<li class="separator"></li>
				<li class="button pubarticle" id="publish"><a href='#'>Objavi izabrane</a></li>
				<li class="button unpubarticle" id="unpublish"><a href="#">Makni izabrane</a></li>
			</ul>
		    <script type="text/javascript">
		    	 $(document).ready(function() {
			    	$("#publish").click(
			    		function(event) { 
			    			$("#articles").attr({action: "<?= $this->baseUrl . "/admin/article/publish" ?>"});  
			    			if(testCheckboxes()) $("#articles").submit(); 
			    			else window.alert("Nije selektiran ni jedan članak.");
			    			event.preventDefault(); 
			    		});
			    		
			    	$("#unpublish").click(
			    		function(event) { 
			    			$("#articles").attr({action: "<?= $this->baseUrl . "/admin/article/unpublish" ?>"});  
			    			if(testCheckboxes()) $("#articles").submit(); 
			    			else window.alert("Nije selektiran ni jedan članak.");
			    			event.preventDefault(); 
			    		});
			    		
			    	$("#delete").click(
			    		function(event) {
			    			if(testCheckboxes())
			    			{
					    		if(window.confirm("Da li stvarno želite izbrisati "+countChecked()+" članak(a)?"))
					    		{
					    			$("#articles").attr({action: "<?= $this->baseUrl . "/admin/article/delete" ?>"});
									$("#articles").submit();  
					    		}
					    	}
					    	else window.alert("Nije selektiran ni jedan članak.");
			    		});
			    		
			    	$("#checkall").click(function() { checkAll(); } );
			    	function testCheckboxes()
			    	{
			    		var i = 1;		    		
			    		while($("#id"+i).length)
			    		{
			    			if($("#id"+i+":checked").length) return true;
			    			i++;
			    		}
			    		return false;
			    	}
			    	
			    	function checkAll()
			    	{
			    		var i = 1;	
			    		var ch = "";
			    		if($("#checkall").attr("checked")) ch = "checked"; else ch = "";	    		
			    		while($("#id"+i).length)
			    		{
			    			$("#id"+i).attr("checked", ch);
			    			i++;
			    		}
			    	}
			    	
			    	function countChecked()
			    	{
						var res = $("input[@type=checkbox][@checked]").length;
						if($("#checkall[@checked]").length) res--;
						return res;
			    	}
			    });
		    </script>
		    <br/>
			<?= $this->form("articles", array("method" => "post", "action" => "noaction")) ?>
				<table width="100%" class="list">
					<tr>					
						
						<th width="3%" class="center">#</th>
						<th width="3%" class="center"><?= $this->formCheckbox('checkall', '', array('title' => 'Uključi/isključi sve')); ?></th>
						<th width="3%" class="center"><acronym title="Objavljen - Pokazuje da li je članak objavljen ili ne.">Obj.</acronym></th>
						<th width="36%">Naslov</th>
						<th width="20%"><acronym title="Kratki naslov za članak bez razmaka i specijalnih znakova. Mora biti jedinstven.">Slug</acronym></th>
						<th width="5%">Red.</th>
						<th width="15%">Zadnja promjena</th>
						<th width="15%">Autor</th>
					</tr>
					<?php $i = 1; ?>
					<?php foreach($this->articles as $article): ?>
						<?php if($article->published == 1): ?>
							<?php $p = "icon_light_bulb.png"; $t = "Makni"; $a = "unpublish";  ?>
						<?php else: ?> 
							<?php $p = "icon_light_bulb_off.png"; $t = "Objavi"; $a = "publish"; ?> 
						<?php endif; ?>
						
						<?php if($i % 2 == 0): ?>
							<?php $c = ' class="hilite" ';  ?>
						<?php else: ?> 
							<?php $c = ''; ?> 
						<?php endif; ?>
						
						<?php $arrows = ""; ?>
						<?php if($i != 1): ?>
							<?php $arrows .= '<a href="'.$this->baseUrl() . "/admin/article/moveup/id/". $article->id . '"><img src="'.$this->baseUrl(). "/images/icon_arrow_up.png" . '" /></a>';  ?>
						<?php else: $arrows .= '<img src="'.$this->baseUrl(). "/images/icon_spacer.png" . '" />'; endif; ?>
						<?php if($i != count($this->articles)): ?> 
							<?php $arrows .= '<a href="'.$this->baseUrl() . "/admin/article/movedown/id/". $article->id . '"><img src="'.$this->baseUrl(). "/images/icon_arrow_down.png" . '" /></a>';  ?>
						<?php endif; ?>
	
					<tr<?= $c ?>>					
						<td width="3%" class="center"><?= $i ?>.</td>
						<td width="3%" class="center"><?= $this->formCheckbox('id'.$article->id, '1'); ?></td>
						<td width="3%" class="center"><a href="<?= $this->baseUrl() . "/admin/article/" . $a . "/id/" . $article->id; ?>" title="<?= $t ?>"><img src="<?= $this->baseUrl() . "/images/" . $p; ?>" /></a></td>
						<td width="36%"><?= $article->title; ?></td>
						<td width="20%"><?= $article->slug; ?></td>
						<td width="5%"><?= $arrows; ?></td>
						<td width="15%"><?= $article->modified; ?></td>
						<td width="15%"><?= $article->fullname; ?></td>
						<?php $i++; ?>
					</tr>
					<?php endforeach; ?>
				</table>
			</form>
	</div>
</div>