<div id="userinfo"><p>Dobrodošli, <?= $this->user->fullname ?> | <a href="<?= $this->baseUrl() ?>/admin/auth/logout">Logout</a></p></div>
<div class="container_12" id="midsection">
	<div class="grid_12">
		<ul class="toolbar">
			<li class="button save" id="save"><a href="#">Spremi</a></li>
			<li class="button save" id="publish"><a href="#">Spremi i objavi</a></li>
			<li class="button delarticle" id="delete"><a href="#">Odustani</a></li>
		</ul>
	</div>
	<script language="javascript" type="text/javascript">
		var lock = false; 
		$(document).ready(function() {
			
			$("#title").slug({hide: false, lock: lock });
			$("#lock").click( function(event) {
				if(lock == false)
				{
					$("#lock").attr("src", "<?= $this->baseUrl(); ?>/images/icon_lock.png");
					$("#lock").attr("title", "Zaključano - Moguća je samo ručna promjena sluga.");
					lock = true;
				}
				else
				{
					$("#lock").attr("src", "<?= $this->baseUrl(); ?>/images/icon_lock_unlock.png");
					$("#lock").attr("title", "Otključano - Promjena naslova mjenja i slug");
					lock = false;
				}
			});
			$("#title").focus( function() { if($("#title").attr("value") == "Naslov") $("#title").attr("value", ""); } );
			$("#title").blur ( function() { if($("#title").attr("value") == "") $("#title").attr("value", "Naslov"); } );
			
			$("#save").click( function () {
				if($("#slug").attr("value") == "" ) { window.alert("Ispunite polje za slug."); return; }
				if($("#title").attr("value") == "" ) { window.alert("Ispunite polje za naslov."); return; }
				$("#editor").submit();
			} );
		});
	
		function generateSlug(text)
		{
		    var text_array = text.split(" ");
		    text = text_array.join("-");
		    text = text.toLowerCase()
			return text;
		}
	</script>
	<script language="javascript" type="text/javascript">
		tinyMCE.init({
			mode : "textareas",
			theme : "advanced",
			plugins : "pagebreak", 
			theme_advanced_buttons1 : "bold,italic,underline,strikethrough,separator,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink,image,separator,pagebreak",
			theme_advanced_buttons2 : "",
			theme_advanced_buttons3 : "",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]"
		});
	</script>
	<div class="grid_12">
		<form method="post" action="<?= $this->baseUrl(); ?>/admin/article/save" class="editor" name="editor" id="editor">
			<input type="hidden" name="category" value="news" />
			<div id="content" style="margin-top: 20px;" class="grid_9 alpha">				
					<p><input type="text" name="title" id="title" class="big" value="Naslov" /></p>
					<p><input type="text" name="slug" id="slug" class="slug"  /> <a href="#"><img id="lock" src="<?= $this->baseUrl(); ?>/images/icon_lock_unlock.png" title="Otključano - Promjena naslova mjenja i slug."/></a></p>
					<p><textarea name="text" style="width: 100%;" rows="15" id="text">This is some content that will be editable with TinyMCE.</textarea></p>				
			</div>
			<div class="grid_3 omega sidebar">
				<h3>Opcije</h3>
				<p><?= $this->formCheckbox("published") ?> Članak je objavljen</p>
			</div>
		</form>
	</div>
</div>