<div id="messagebar"><div id="message" style="display: none"><?= $this->message ?></div></div>
<div id="userinfo"><p>Dobrodošli, <?= $this->user->fullname ?> | <a href="<?= $this->baseUrl() ?>/admin/auth/logout">Logout</a></p></div>
<div class="toolbar">
	<div class="container_12" id="midsection">
			<ul>

			</ul>
	</div>
</div>

<div class="container_12" id="midsection">
	<div id="content" class="grid_12">
		<p>Greška: Nije moguće brisati stavke koje imaju podstavke.</p>
	</div>
</div>