<div id="messagebar"><div id="message" style="display: none"><?= $this->message ?></div></div>
<div id="userinfo"><p>Dobrodošli, <?= $this->user->fullname ?> | <a href="<?= $this->baseUrl() ?>/admin/auth/logout">Logout</a></p></div>
<div class="toolbar">
	<div class="container_12" id="midsection">
			<ul>
				<li class="button newarticle" id="newtext"><a href="<?= $this->baseUrl() ?>/admin/sidebar/newtext/">Novi tekst</a></li>
				<li class="button newarticle" id="newpoll"><a href="<?= $this->baseUrl() ?>/admin/sidebar/newpoll/">Nova anketa</a></li>
				<li class="separator"></li>
				<li class="button delarticle" id="delete"><a href="#">Izbriši izabrane</a></li>
				<li class="button pubarticle" id="publish"><a href='#'>Objavi izabrane</a></li>
				<li class="button unpubarticle" id="unpublish"><a href="#">Makni izabrane</a></li>
			</ul>
	</div>
</div>

<div class="container_12" id="midsection">
	<div id="content" class="grid_12">
		    <script type="text/javascript">		    
		    
		    	 $(document).ready(function() {
			    	$("#publish").click(
			    		function(event) { 
			    			$("#sidebars").attr({action: "<?= $this->baseUrl . "/admin/sidebar/publish" ?>"});  
			    			if($("input[@type='checkbox']").checkCount()) $("#sidebars").submit(); 
			    			else showMessage("Greška: Nije selektiran ni jedan članak."); 
			    			
			    			event.preventDefault(); 
			    		});   	
			    		
			    	$("#unpublish").click(
			    		function(event) { 
			    			$("#sidebars").attr({action: "<?= $this->baseUrl . "/admin/sidebar/unpublish" ?>"});  
			    			if($("input[@type='checkbox']").checkCount()) $("#sidebars").submit(); 
			    			else showMessage("Greška: Nije selektiran ni jedan članak."); 
			    			event.preventDefault(); 
			    		});
			    		
			    	$("#delete").click(
			    		function(event) {
			    			$("#sidebars").attr({action: "<?= $this->baseUrl . "/admin/sidebar/delete" ?>"});  
			    			if($("input[@type='checkbox']").checkCount()) $("#sidebars").submit(); 
			    			else showMessage("Greška: Nije selektiran ni jedan članak."); 
			    			event.preventDefault(); 
			    		});
			    		
			    	$("#checkall").click( function ()
			    	{
						if($("#checkall").attr("checked"))
							$("input[@type='checkbox']").check('on');
						else
							$("input[@type='checkbox']").check('off');
			    	});
			    	
			    	function testCheckboxes()
			    	{
			    		var i = 1;		    		
			    		while($("#id"+i).length)
			    		{
			    			if($("#id"+i+":checked").length) return true;
			    			i++;
			    		}
			    		return false;
			    	}
			    	
			    	function checkAll()
			    	{
			    		var i = 1;	
			    		var ch = "";
			    		if($("#checkall").attr("checked")) ch = "checked"; else ch = "";	    		
			    		while($("#id"+i).length)
			    		{
			    			$("#id"+i).attr("checked", ch);
			    			i++;
			    		}
			    	}
			    	
			    	function countChecked()
			    	{
						var res = $("input[@type=checkbox][@checked]").length;
						if($("#checkall[@checked]").length) res--;
						return res;
			    	}
			    });
		    </script>
		    <h2>Sidebar</h2>
			<?= $this->form("sidebars", array("method" => "post", "action" => "noaction")) ?>
				<table width="100%" class="list">
					<tr>
						
						<th width="3%" class="center">#</th>
						<th width="3%" class="center"><?= $this->formCheckbox('checkall', '', array('title' => 'Uključi/isključi sve', 'class' => 'nocount')); ?></th>
						<th width="5%" class="center"><acronym title="Objavljen - Pokazuje da li je članak objavljen ili ne.">Obj.</acronym></th>
						<th width="8%">Tip</th>
						<th width="51%">Naslov</th>
						<th width="5%">Red.</th>
						<th width="10%" class="center">Prikazan na</th>
						<th width="10%" class="center">Pozicija</th>

					</tr>
					<?php $i = 1; ?>
					<?php foreach($this->sidebars as $item):
						if($item->published == 1):
							$p = "icon_light_bulb.png"; $t = "Makni"; $a = "unpublish";
						else:
							$p = "icon_light_bulb_off.png"; $t = "Objavi"; $a = "publish";
						endif;
						
						if($i % 2 == 0):
							$c = ' class="hilite" ';
						else:
							$c = '';
						endif;
						
						$arrows = "";
						if($i != 1):
							$arrows .= '<a href="'.$this->baseUrl() . "/admin/sidebar/moveup/id/". $item->id . '"><img src="'.$this->baseUrl(). "/images/icon_arrow_small_up.png" . '" title="Pomakni gore" /></a>';
						else: $arrows .= '<img src="'.$this->baseUrl(). "/images/icon_spacer.png" . '" />'; endif;
						if($i != count($this->sidebars)):
							$arrows .= '<a href="'.$this->baseUrl() . "/admin/sidebar/movedown/id/". $item->id . '"><img src="'.$this->baseUrl(). "/images/icon_arrow_small_down.png" . '" /></a>';
						endif; 
						
						$date = new Zend_Date(Zend_Date::now(), Zend_Date::ISO_8601);
						$created = $date->toString("dd.MM.YY. HH:mm");
						
						if($item->count % 10 > 1 && $item->count % 10 < 5)
							$str = "stranice";
						else
							$str = "stranica"; 
							
							if($item->type == "Tekst")
								$link = $this->baseUrl() . "/admin/sidebar/edittext/id/" . $item->id;
							elseif($item->type == "Anketa")
								$link = $this->baseUrl() . "/admin/sidebar/editpoll/id/" . $item->id;
						?>
	
					<tr<?= $c ?>>					
						<td width="3%" class="center"><?= $i ?>.</td>
						<td width="3%" class="center"><?= $this->formCheckbox('id'.$item->id, '1'); ?></td>
						<td width="5%" class="center"><a href="<?= $this->baseUrl() . "/admin/sidebar/" . $a . "/id/" . $item->id; ?>" title="<?= $t ?>"><img src="<?= $this->baseUrl() . "/images/" . $p; ?>" /></a></td>
						<td width="8%"><?= $item->type ?></td>
						<td width="51%"><a href="<?= $link ?>" title="Izmjeni sidebar"><?= $item->title; ?></a></td>
						<td width="5%"><?= $arrows; ?></td>
						<td width="10%" class="center"><?= $item->count ?> <?= $str ?></td>
						<td width="10%" class="center"><?= $item->position ?></td>
						<?php $i++; ?>
					</tr>
					<?php endforeach; ?>
				</table>
			</form>
	</div>
</div>