<div class="container_12" id="midsection">
	<div class="grid_10 prefix_1 suffix_1">
		<div id="content" class="grid_10 alpha">
			<?php foreach($this->news as $entry) : ?>
				<h3><?= $this->escape($entry->title) ?></h3>
				<p><?php echo $this->escape($entry->intro);?></p>
				<p><?php echo $this->escape($entry->text);?></p>
			<?php endforeach; ?>
			
			<?php foreach($this->mainmenu as $entry) : ?>
				<p><?= $entry->slug ?></p>
			<?php endforeach; ?>
		</div>
	</div>
</div>