<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/styles/master.css" type="text/css" media="screen" charset="utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/styles/admin.css" type="text/css" media="screen" charset="utf-8" />
	<script src="<?=$this->baseUrl()?>/scripts/jquery-1.2.6.min.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/scripts/jquery.slug.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/scripts/jquery.pause.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/scripts/jquery.custom.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl()?>/tiny_mce/tiny_mce.js" type="text/javascript"></script>
	<title>Prospekta - Administracija: <?=$this->escape($this->title)?></title>
</head>
<body>
<div id="adminmenu">
	<ul>
		<li><strong>Prospekta Administracija: </strong></li>
		<li><a href="<?= $this->baseUrl() ?>/admin">Pregled</a></li>
		<li><a href="<?= $this->baseUrl() ?>/admin/article">Članci</a></li>				
		<li><a href="<?= $this->baseUrl() ?>/admin/page">Stranice</a></li>
		<li><a href="<?= $this->baseUrl() ?>/admin/menu">Izbornik</a></li>
		<li><a href="<?= $this->baseUrl() ?>/admin/sidebar">Sidebar</a></li>
		<li><a href="<?= $this->baseUrl() ?>/sspdir">Galerija</a></li>
		<li><a href="<?= $this->baseUrl() ?>/admin/file">Datoteke</a></li>
	</ul>
</div>
<?= $this->layout()->content; ?>
	<p style="clear: both; text-align: center; padding-top: 30px;">
		&copy; 2008 Prospekta
	</p>
</body>
</html>