<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/styles/master.css" type="text/css" media="screen" charset="utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/styles/admin.css" type="text/css" media="screen" charset="utf-8" />
	<script src="<?=$this->baseUrl()?>/scripts/jquery-1.2.6.min.js" type="text/javascript"></script>
	<title>Prospekta - Edukacija i zapošljavanje mladih: <?=$this->escape($this->title)?></title>
</head>
<body>
<div id="header"><div class="logo"></div><h1>Prospekta - Edukacija i zapošljavanje mladih: <?=$this->escape($this->title); ?></h1></div>
<div id="menu">
	<ul>
		<script type="text/javascript">
		 	function showTab(number)
		 	{
		 		for(i=1; i<5; i++)
		 		{
		 			$('#submenu-tab'+i).hide(500);
		 		}
		 		$('#submenu-tab'+number).show(500);
		 	}
		</script>
		<li class="med"><a href="<?= $this->baseUrl() ?>/admin"><strong>Početna</strong></a></li>
		<li class="med"><a href="<?= $this->baseUrl() ?>/admin/article"><strong>Članci</strong></a></li>				
		<li class="med"><a href="<?= $this->baseUrl() ?>/admin/page"><strong>Stranice</strong></a></li>
		<li class="big"><a href="<?= $this->baseUrl() ?>/admin/menu"><strong>Izbornik</strong></a></li>
		<li class="big"><a href="<?= $this->baseUrl() ?>/admin/module"><strong>Moduli</strong></a></li>
		<li class="big"><a href="<?= $this->baseUrl() ?>/admin/module"><strong>Korisnici</strong></a></li>
		<li class="big"><a href="<?= $this->baseUrl() ?>/admin/files"><strong>Datoteke</strong></a></li>
	</ul>
</div>
<div class="border-bottom"></div>
<?= $this->layout()->content; ?>
</body>
</html>