<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="Prospekta je organizacija usmjerena na edukaciju i zapošljavanje mladih. Kroz naše programe osobnog i profesionalnog razvoja stvaramo grupe mladih i uspješnih pojedinaca, koji su traženi na tržištu rada zbog svojih izuzetnih vještina i sposobnosti. Uz stručno vodstvo naših trenera, polaznici u Prospekti ostvaruju dodatnu vrijednost na svoje obrazovanje." />
	<meta name="keywords" content="Studenti, Osobni razvoj, Zapošljavanje, Karijera, Edukacija, Soft skills, Profesionalno usmjeravanje, Radionice, Vizija, Timski rad" />

	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/styles/master.css" type="text/css" media="screen" charset="utf-8" />
	<script src="<?=$this->baseUrl()?>/scripts/jquery-1.2.6.min.js" type="text/javascript"></script>
	<title>Prospekta - Edukacija i zapošljavanje mladih: <?=$this->escape($this->title)?></title>

<script type="text/javascript">
	$.fn.togglemenu = function()
	{
		this.siblings(".submenu").fadeOut(200);
		this.fadeIn(200);
	}
	
	var images = new Array("pol1_inovativnost.jpg", "pol2_edukacija.jpg", "pol1_kreativnost.jpg", "pol2_entuzijazam.jpg", "pol1_profesionalnost.jpg", "pol2_interakt.jpg", "pol1_vizionarstvo.jpg", "pol2_pouzdanost.jpg", "pol1_zajednistvo.jpg", "pol2_timskirad.jpg", "pol2_zabava.jpg");
	for(i=0; i<images.length; i++)
	{
		var img = new Image(10, 10);
		img.src = "images/"+images[i];
	}
	
	
	function slideshow(counter)
	{
		var curimage = counter % images.length;
		var nextimage = (counter+1) % images.length;
		if(counter % 2 == 0)
		{
			$('#polaroid2').css("background-image", "url(images/"+images[curimage]+")");
			$('#polaroid1').fadeOut("slow");
			$('#polaroid2').fadeIn("slow");			
		}
		else
		{
			$('#polaroid1').css("background-image", "url(images/"+images[curimage]+")");
			$('#polaroid2').fadeOut("slow");
			$('#polaroid1').fadeIn("slow");
		}
		counter++;
		setTimeout("slideshow("+counter+")", 5000);
	}
	


	$(document).ready(function() {
		
		$('#menuitem1').mouseover(function() { $('#subtab1').togglemenu(); });
		<?php for($i = 2; $i <= $this->menucounter; $i++): ?>
			$('#menuitem<?= $i ?>').mouseover(function() { $('#subtab<?= $i ?>').togglemenu(); });
		<?php endfor; ?>

		$('#menu').hover(function() {}, function() { $('#subtab1').togglemenu(); });
		
		slideshow(Math.floor(Math.random() * (images.length)));
	});
</script>
</head>
<body>
<div id="header"><div class="logo"></div></div>
<div class="border-top"></div>

<div id="menu">		
		<ul id="topmenu" >
			<li class="topitem" id="menuitem1"><a href="<?= $this->baseUrl() ?>"><strong>Početna</strong></a></li>
			<?= $this->topmenu ?>
		</ul>
		<div id="subtab1" class="submenu">
			<div class="introtext"><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras volutpat nunc lacinia dolor. Mauris enim justo, vehicula et, commodo vel, tincidunt eget, ipsum. Donec justo orci, luctus sit čamet, placerat ćeu, malesuada sit amet, libero. Duis volutpat tempor lectus. Morbi placerat malesuada nulla. Duis viverra nisl at nibh. Nam eget sem sit amet šest varius auctor. Cras sem. Ut hendrerit, libero đut porta ornare, žipsum ipsum consectetuer est, ut tristique lectus mi ac eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Quisque sit amet mauris sit amet urna bibendum faucibus. Vivamus lobortis ante quis nunc. Mauris ornare dolor ac nunc. </p></div>
			<div class="polaroids"><div style="" id="polaroid1" ></div><div style="display: none;" id="polaroid2" ></div></div>
		</div>
		<?= $this->submenu ?>
</div>

<div id="programi" class="orange"> 
	<div class="container_12" style="margin-left: auto; margin-right: auto;">
		<div id="prog1" class="grid_4 alpha program">
			<h2>Career Coaching Program</h2>
			<a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/prog1_career.jpg" /></a>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras volutpat nunc lacinia dolor. Mauris enim justo, vehicula et, commodo vel, tincidunt eget, ipsum.</p>
		</div>
		<div id="prog2" class="grid_4 program">
			<h2>Self-Development Program</h2>
			<a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/prog2_selfdev.jpg" /></a>
			<p> Donec justo orci, luctus sit čamet, placerat ćeu, malesuada sit amet, libero. Duis volutpat tempor lectus. Morbi placerat malesuada nulla. Duis viverra nisl at nibh. </p>
		</div>
		<div id="prog3" class="grid_4 omega program">
			<h2>Student Management Program</h2>
			<a href="#"><img src="<?php echo $this->baseUrl(); ?>/images/prog3_student.jpg" /></a>
			<p>Nam eget sem sit amet šest varius auctor. Cras sem. Ut hendrerit, libero đut porta ornare, žipsum ipsum consectetuer est, ut tristique lectus mi ac eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
		</div>
	</div>
	<span class="clear"></span>
</div>

<div class="border-bottom"></div>

<?= $this->layout()->content; ?>

<span class="clear"></span>

<div class="border-top"></div>
<div id="footer" class="orange"> 
	<div class="container_12">
		<div class="grid_3 alpha"><h2>Preporuči prijatelju</h2>
			<form action="/mail/preporuka" method="post">
				<div><label for="ime">Tvoje ime </label><br /><input type="text" id="ime" class="text" /><br /></div>
				<div><label for="email">e-mail prijatelja </label><br /><input type="text" id="email" class="text" /></div>
				<div class="button"><input type="submit" value="Pošalji &raquo;" class="button" /></div>
			</form>
		</div>
		<div class="grid_6">
			<h2>Feedback naših polaznika</h2>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras volutpat nunc lacinia dolor. Mauris enim justo, vehicula et, commodo vel, tincidunt eget, ipsum. Donec justo orci, luctus sit čamet, placerat ćeu, malesuada sit amet, libero. Duis volutpat tempor lectus. Morbi placerat malesuada nulla. Duis viverra nisl at nibh.</p>
		</div>
		<div class="grid_3 omega"><h2>Prijavi se na newsletter</h2>
			<form action="/mail/preporuka" method="post">
				<div><label for="newsime">Ime </label><input type="text" id="newsime" class="text" /><br /></div>
				<div><label for="newsemail">e-mail </label><input type="text" id="newsemail" class="text" /></div>
				<div class="button"><input type="submit" value="Pošalji &raquo;" class="button" /><br /><br /><a href="#">Odjavi se</a></div>
			</form>
		</div>
	</div>
	<span class="clear"></span>
</div>
<div class="border-bottom"></div>
<div class="prijava"><a href="#" title="Prijavi se još danas!"><img src="<?= $this->baseUrl() ?>/images/ui_prijava.jpg" alt="Prijavi se još danas!"/></a></div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-189848-3");
pageTracker._trackPageview();
</script>
</body>
</html>