<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/styles/master.css" type="text/css" media="screen" charset="utf-8" />
	<script src="<?=$this->baseUrl()?>/scripts/jquery-1.2.6.min.js" type="text/javascript"></script>
	<title>Prospekta - Edukacija i zapošljavanje mladih: <?=$this->escape($this->title)?></title>
</head>
<body>
<script type="text/javascript">


	$.fn.togglemenu = function()
	{
		this.siblings(".submenu").fadeOut(200);
		this.fadeIn(200);
	}
	

	$(document).ready(function() {
		$('#menuitem1').mouseover(function() { $('#subtab1').togglemenu(); });
		$('#menuitem2').mouseover(function() { $('#subtab2').togglemenu(); });
		$('#menuitem3').mouseover(function() { $('#subtab3').togglemenu(); });
		$('#menuitem4').mouseover(function() { $('#subtab4').togglemenu(); });
		$('#menuitem5').mouseover(function() { $('#subtab5').togglemenu(); });
		$('#menuitem6').mouseover(function() { $('#subtab6').togglemenu(); });
		$('#menuitem7').mouseover(function() { $('#subtab7').togglemenu(); });
		$('#menu').hover(function() {}, function() { $('#subtab1').togglemenu(); });

	});
</script>
<div id="header"><div class="logo"></div><h1>Prospekta - Edukacija i zapošljavanje mladih: <?=$this->escape($this->title); ?></h1></div>
<div id="menu"> 
		
		<ul id="topmenu" >
			<li class="topitem" id="menuitem1"><a href="#">Početna</a></li>
			<li class="topitem" id="menuitem2"><a href="#">O nama</a>	</li>
			<li class="topitem" id="menuitem3"><a href="#">Programi edukacija</a></li>
			<li class="topitem" id="menuitem4"><a href="#">Posao i karijera</a></li>
			<li class="topitem" id="menuitem5"><a href="#">Zanimljivo i korisno</a></li>
			<li class="topitem" id="menuitem6"><a href="#">Kontakt</a></li>
		</ul>
		<div id="subtab1" class="submenu"><p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras volutpat nunc lacinia dolor. Mauris enim justo, vehicula et, commodo vel, tincidunt eget, ipsum. Donec justo orci, luctus sit čamet, placerat ćeu, malesuada sit amet, libero. Duis volutpat tempor lectus. Morbi placerat malesuada nulla. Duis viverra nisl at nibh. Nam eget sem sit amet šest varius auctor. Cras sem. Ut hendrerit, libero đut porta ornare, žipsum ipsum consectetuer est, ut tristique lectus mi ac eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Quisque sit amet mauris sit amet urna bibendum faucibus. Vivamus lobortis ante quis nunc. Mauris ornare dolor ac nunc. Duis fringilla, lorem vel cursus gravida, augue augue hendrerit enim, sed imperdiet urna mauris sit amet quam.</p></div>
		<ul class="submenu" id="subtab2" style="display: none">
			<li><a href="#">Tko smo mi?</a></li>
			<li><a href="#">Naše vrijednosti</a></li>
			<li><a href="#">Naša vizija</a></li>
			<li><a href="#">Naša misija</a></li>
			<li><a href="#">Management<br />i treneri</a></li>
		</ul>	
		<ul class="submenu" id="subtab3" style="display: none;">
			<li><a href="#">Career coaching</a></li>
			<li><a href="#">Self-development</a></li>
			<li><a href="#">Student management</a></li>
		</ul>
		<ul class="submenu" id="subtab4" style="display: none;">
			<li><a href="#">Tražim posao!</a></li>
			<li><a href="#">Korisno je znati...</a></li>
			<li><a href="#">Opisi radnih mjesta</a></li>
			<li><a href="#">Karijera u...</a></li>
			<li><a href="#">Oglasi za posao</a></li>
		</ul>
		<ul class="submenu" id="subtab5" style="display: none;">
			<li><a href="#">Što čitati?</a></li>
			<li><a href="#">Što gledati?</a></li>
			<li><a href="#">Što posjetiti</a></li>
			<li><a href="#">Što slušati</a></li>
			<li><a href="#">Linkovi za studente</a></li>
			<li><a href="#">Za vašu inspiraciju</a></li>
			<li><a href="#">Nepoznato o poznatima</a></li>
			<li><a href="#">Znate li da...?</a></li>
			<li><a href="#">Tema tjedna</a></li>
		</ul>

		<ul class="submenu" id="subtab6" style="display: none;">
			<li><a href="#">Kako do nas?</a></li>
			<li><a href="#">Prijave</a></li>
		</ul>
</div>



<?= $this->layout()->content; ?>
</body>
</html>